{% set name = "jaraco.logging" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fcb2c3f12351d4d50375b6b60f3899c5837b232f1a2d8ffcbaff5ecd2b733e7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python >=3.6
    - tempora
    - six
    - setuptools

test:
  imports:
    - jaraco
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/jaraco.logging
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: jaraco.logging
  dev_url: https://github.com/jaraco/jaraco.logging

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
