{% set name = "jaraco.logging" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaraco_logging-{{ version }}.tar.gz
  sha256: e7d6dc8368477ce69eb1d6ed851d805896a1ca942ce3fd1773580311b0b775fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=1.15.0
    - setuptools
  run:
    - python >={{ python_min }}
    - tempora
    - six
    - setuptools

test:
  imports:
    - jaraco
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jaraco/jaraco.logging
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: jaraco.logging
  dev_url: https://github.com/jaraco/jaraco.logging

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
