{% set name = "jaraco.logging" %}
{% set version = "1.5.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "e4eac879927ecb2065c0631d2c8bb36c16138c5085c57db055bdfee2fdb709a8" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.15.0

  run:
    - python
    - tempora
    - six

test:
  imports:
    - jaraco

about:
  home: https://github.com/jaraco/jaraco.logging
  # license_file: jaraco doesn't include license files - see https://github.com/jaraco/skeleton/issues/1
  license: MIT
  license_family: MIT
  summary: 'jaraco.logging'
  dev_url: https://github.com/jaraco/jaraco.logging

extra:
  recipe-maintainers:
    - pmlandwehr
