{% set name = "jaraco.logging" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4a7cfbacb86a834c2886c01a3b52bc4cde2728c1d9717c49d4dce1d6248f07b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python >=3.6
    - tempora
    - six
    - setuptools

test:
  imports:
    - jaraco
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/jaraco.logging
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: jaraco.logging
  dev_url: https://github.com/jaraco/jaraco.logging

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
