{% set name = "jaraco.logging" %}
{% set version = "3.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "150dc8701207b28bc65a16f0e91c07250a8d1b9da324ce674c0e375774944f13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python
    - tempora
    - six
    - setuptools

test:
  imports:
    - jaraco

about:
  home: https://github.com/jaraco/jaraco.logging
  # license_file: jaraco doesn't include license files - see https://github.com/jaraco/skeleton/issues/1
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: jaraco.logging
  dev_url: https://github.com/jaraco/jaraco.logging

extra:
  recipe-maintainers:
    - pmlandwehr
