schema_version: 1

context:
  name: jaraco.logging
  version: "3.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jaraco_logging-${{ version }}.tar.gz
  sha256: e7d6dc8368477ce69eb1d6ed851d805896a1ca942ce3fd1773580311b0b775fb

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools_scm >=1.15.0
    - setuptools
  run:
    - python >=${{ python_min }}
    - tempora
    - six
    - setuptools

tests:
  - python:
      imports:
        - jaraco
      pip_check: true
      python_version: ${{ python_min }}

about:
  license_file: LICENSE
  license: MIT
  summary: jaraco.logging
  homepage: https://github.com/jaraco/jaraco.logging
  repository: https://github.com/jaraco/jaraco.logging

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
