travis:
  secure:
    BINSTAR_TOKEN: fsF9I80yjzGVCn3qzYkJQ/RL2GcjYwuT2ziR4n5yPeut69dxvi8/Coj+QaBcySfoJIOcbL+Sdl12IwGXU+5NB5/SfJNfk3Xi1WnczZ33DiHWrWzqHyp6iGBo2iuAD7HFQTXYZxuJ3d2Qc7mfr3Aj8yQZIdahowyMFjMKJENXLqE+RCtq+0Es8PVHVsODkSkeSXpagD6YGXvI9W3UmlStbeT/oKHxV/hMRyJ0qJt9rZd5LkVDiMYLWqXUio3UJoNulGGnGNzCKnQRkPh9QrtRqxuCSOp5ZGMhIG7dxd6RWzwy9PEJ/fS+sTknDmWo6X3vo1JHMDgP1wXE/IwvDKxEvSdT/FIGC3A1sPLd/H+DaceOF1nt5P5cWggZLi8isBcdeuIFH1o5+uDz58AYDZZw8yWV+17bLXrVoFki+h0qB2wbi+GO7V2ihMsssgGpEW1DrvhyDzDxLhCn7PVl1TeBCJma3CwZRS+TSma1GkVcHZ2BiwJ8l4DkNyxormLIhrUcWgv8qh0ZwKE/fVvw7QmGUnurdwkG9Q7O5CU8BrJG6ehYgW7j0Fdb9evZSadQTpAg6dUrsRJmNMgA7KszeXtFcLsx00RKtmsZ9DjY+w3PPpH4ujYANt9pPo2/8Rb3RWiIW4T7YdEHnwlUsGHiQMxgCNOA9nmxTJnMZsQQ400hlBw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
