travis:
  secure:
    BINSTAR_TOKEN: Dn/0LoHsoi7UHGsuoigXXf/+DoYYaxZwrEiQiM6deQwAkmJ1DxmAn1vlFwrWh3DdVoc2ygyu1nd1JapqdkWOLhe7jJVsVLJOPX4z9zpgp9GvQBT23LADrWsUIlToVcIlxA43Z5KEp0EelHU7JgEsmGv+15Tz12oBngfhqDqARhJJHMv/HG2ipYqhfJqoatxICCpRFNlMnKHwOVVILzGLUl2wHCrzP/ZAEEZDG4hkliSsoFXvoAqyHGHMN+gNeNve9MvAKDnaT0gjhWSNB/1o+v+Hm29oXMPLcKKV1xbGPdXssTR9wnlBe7hgwC33ODL8nOJKvMAwBRl4TyOzxoAd75IZbDt2wCYr/QC8mos/f9WLs/NsYT3O/kLm1vEa4UKWyQgxEmgCWelTKNxbdQc/bO0NSnCYRP9J23+uIj68rXlXYVtN3CkQZ2YVLL+2eyxMBXDyAKwT62t65TrD9QQIzKsjJvRrZJsteWN7t5ajkj2C02jboJGdR6QxSw8P1sAGAXv+MsWGPwZy+dQbZjkUNXEPUT7dOGRBgw3BcnIUqun4cWvp69GfgP1pFq6NAHqO7o4EOTRdhadjDTqkVwZMlLxwud6b11JDNKuBw+60BrpQB40OKOFBIq4OI22Xgy26YQa2IQCiQcE6saD9mnLTR6ZQJ0y3o5cj4pZZ6nPfXmM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
